name: remote ssh command
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.13.0"
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.MPA_SSH_HOST }}
          username: root
          password: ${{ secrets.MPA_SSH_PASSWORD }}
          script: |
            cd production-env/
            if [ ! -d "mpa-coaching-admin-portal-react" ]; then
              git clone https://${{ secrets.GIT_TOKEN }}@github.com/Mpa-Coaching/mpa-coaching-admin-portal-react.git
            else
              echo "Repository already exists."
            fi
            cd mpa-coaching-admin-portal-react
            git checkout main
            git reset --hard
            git pull
            echo "Installing dependencies..."
            /root/.nvm/versions/node/v22.13.0/bin/npm install
            echo "Building the project..."
            /root/.nvm/versions/node/v22.13.0/bin/npm run build
            echo "Copying build to web server directory..."
            mkdir -p /var/www/html/mpa-coaching-admin-portal-react
            cp -r dist/* /var/www/html/mpa-coaching-admin-portal-react/
            echo "Restarting nginx..."
            systemctl restart nginx
